const jokes = [
  "Why don't scientists trust atoms? Because they make up everything.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "How does a snowman get around? By riding an 'icicle.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the math book look sad? Because it had too many problems.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "How does a snowman get around? By riding an 'icicle.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's orange and sounds like a parrot? A carrot.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why can't you hear a pterodactyl using the bathroom? Because the 'P' is silent!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why are frogs so happy? They eat whatever bugs them.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a seafood diet. I see food and I eat it.",
  "What do you get when you cross a snowman with a dog? Frostbite.",
  "I couldn't figure out how the seatbelt worked. Then it just clicked.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why was the math book sad? Because it had too many problems.",
  "I'm friends with all electricians. We have great current connections.",
  "I'm friends with all electricians. We have great current connections.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "What do you call a fish wearing a crown? A kingfish.",
  "I'm friends with all electricians. We have great current connections.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I used to play piano by ear, but now I use my hands.",
  "I'm friends with all electricians. We have great current connections.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why can't you give Elsa a balloon? Because she will let it go.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "I used to be a baker, but I couldn't make enough dough.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why can't you hear a pterodactyl using the bathroom? Because the 'P' is silent!",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's orange and sounds like a parrot? A carrot.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why are frogs so happy? They eat whatever bugs them.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a seafood diet. I see food and I eat it.",
  "What do you get when you cross a snowman with a dog? Frostbite.",
  "I couldn't figure out how the seatbelt worked. Then it just clicked.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why was the math book sad? Because it had too many problems.",
  "I'm friends with all electricians. We have great current connections.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "What do you call a fish wearing a crown? A kingfish.",
  "I'm friends with all electricians. We have great current connections.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I used to play piano by ear, but now I use my hands.",
  "I'm friends with all electricians. We have great current connections.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why can't you give Elsa a balloon? Because she will let it go.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "I used to be a baker, but I couldn't make enough dough.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why can't you hear a pterodactyl using the bathroom? Because the 'P' is silent!",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's orange and sounds like a parrot? A carrot.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "Why are frogs so happy? They eat whatever bugs them.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a seafood diet. I see food and I eat it.",
  "What do you get when you cross a snowman with a dog? Frostbite.",
  "I couldn't figure out how the seatbelt worked. Then it just clicked.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why was the math book sad? Because it had too many problems.",
  "I'm friends with all electricians. We have great current connections.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "What do you call a fish wearing a crown? A kingfish.",
  "I'm friends with all electricians. We have great current connections."
  ];

let jk=jokes[Math.floor(100*Math.random())%95]

document.getElementsByClassName("output")[0].firstElementChild.innerHTML=jk